language: elixir
elixir:
  - 1.8.1
otp_release:
  - 21.0
addons:
  postgresql: '9.4'
notifications:
    email: false
cache:
  directories:
    - _build
    - deps
env:
  - MIX_ENV=test
install:
  - cp config/travis_ci_test.exs config/test.exs
before_script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix do deps.get, ecto.setup
script:
  - mix format --check-formatted
  - mix credo --strict
  - mix test
